### ISSUE TITLE
Before-the-HOL.md contains Reslient IaaS Doc

### ISSUE THREAD

**Issue by evmoreno** [Microsoft/MCW-Continuous-delivery-in-VSTS-and-Azure#3]
Wrong page added into this Repo - https://github.com/Microsoft/MCW-Continuous-delivery-in-VSTS-and-Azure/blob/master/Hands-on%20lab/Before%20the%20HOL.md reads

**Comment by DawnmarieDesJardins** [comment]
Assigning to Michael to review/resolve.
Michael - I added the header and licensing information, but line 26 title says Building a resilient IaaS architecture.  I'm not sure if it was a copy/paste and the title didn't get changed, or the Before the HOL instructions are incorrect.  Please review & resolve.
(Document also needs to have a TOC added).

**Comment by DawnmarieDesJardins** [comment]
Incorrect title, instructions are correct. Corrected and closing issue.
